### ISSUE TITLE
Using HDFToText problem

### ISSUE THREAD

**Issue by qadahtm** [aseldawy/spatialhadoop2#10]
I tried to use HDFToText over MODIS dataset available here:

http://aws.amazon.com/blogs/aws/process-earth-science-data-on-aws-with-nasa-nex/

But, it does not seem to work. Any clue?

Thanks in advanced

**Comment by aseldawy** [comment]
You need to provide the type of output shape as either NASAPoint or NASARectangle.
For NASAPoint, each value is associated with a single latitude and longitude. To use this type, add the argument shape:edu.umn.cs.spatialHadoop.nasa.NASAPoint
For NASARectangle, each value is associated with a rectangle that represents the region covered by each pixel. To use this type, add the argument, shape:edu.umn.cs.spatialHadoop.nasa.NASARectangle
 Let me know if you still have a problem.

**Comment by qadahtm** [comment]
@aseldawy 

Thanks for your reply. I tried your suggestion and I am using the latest version. 
But still having a problem. The MR job starts fine but the mappers throw a null pointer exception and eventually the job fails. Here is the log

=============
2015-06-05 09:21:24,106 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1430764776626_66840_m_000014_0: Error: java.lang.NullPointerException
	at edu.umn.cs.spatialHadoop.nasa.HDFRecordReader.initialize(HDFRecordReader.java:127)
	at edu.umn.cs.spatialHadoop.nasa.HDFRecordReader.initialize(HDFRecordReader.java:95)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.initialize(MapTask.java:524)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:762)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

=============
 
Tracing it back to the code in HDFRecordReader. It seems that the unparsedDataArray is null for some reason (see code below)

```java
if (dd instanceof DDNumericDataGroup) {
        DDNumericDataGroup numericDataGroup = (DDNumericDataGroup) dd;
        unparsedDataArray = numericDataGroup.getAsByteArray();
        valueSize = numericDataGroup.getDataSize();
        resolution = numericDataGroup.getDimensions()[0];
        if (valueSize * resolution * resolution != unparsedDataArray.length)
          throw new RuntimeException("Error parsing metadata");
      } else if (dd instanceof DDVDataHeader) {
```

It seems to me that a bug prevents current implementation from working with the dataset I am using? What do you think?

I am working with the following dataset: MODIS Vegetation Indices MOD13Q1 (Vegetation Indices 16-Day L3 Global 250m) 

Have ever worked with it or tested SpatialHadoop with it?

Thanks for your support

**Comment by aseldawy** [comment]
I looked at this error. It seems that the new HDF library I'm using does not yet support LinkedBlocks which happen to be in vegetation files. I'm working on this issue. Until I resolve it, you can work with other files, such as temperature data (e.g., MOD11A1).

**Comment by aseldawy** [comment]
I made some updates to the HDF support in SpatialHadoop and it should now be able to read LinkedBlocks in HDF files. I tried MOD11A1 files and it worked fine. Of course you need to grab the latest source code as it's not yet released in the stable version.

**Comment by qadahtm** [comment]
Thanks for the update.
