### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0

### ISSUE THREAD

**Issue by awhan-zot** [aseldawy/spatialhadoop2#20]
Compiled from the latest version after git cloning the repo. When I try to run the following

$ bin/shadoop generate test mbr:0,0,1000000,1000000
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Vector.java:744)
        at edu.umn.cs.spatialHadoop.OperationsParams.autoDetectShape(OperationsParams.java:705)
        at edu.umn.cs.spatialHadoop.OperationsParams.getShape(OperationsParams.java:336)
        at edu.umn.cs.spatialHadoop.OperationsParams.getShape(OperationsParams.java:341)
        at edu.umn.cs.spatialHadoop.OperationsParams.<init>(OperationsParams.java:88)
        at edu.umn.cs.spatialHadoop.OperationsParams.<init>(OperationsParams.java:81)
        at edu.umn.cs.spatialHadoop.RandomSpatialGenerator.main(RandomSpatialGenerator.java:220)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:71)
        at org.apache.hadoop.util.ProgramDriver.run(ProgramDriver.java:144)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:152)
        at edu.umn.cs.spatialHadoop.operations.Main.main(Main.java:137)

What is the issue here?

$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

$ hadoop version
Hadoop 2.7.0
Subversion https://git-wip-us.apache.org/repos/asf/hadoop.git -r d4c8d4d4d203c934e8074b31289a28724c0842cf
Compiled by jenkins on 2015-04-10T18:40Z
Compiled with protoc 2.5.0
From source with checksum a9e90912c37a35c3195d23951fd18f
This command was run using /home/hadoopuser/hadoop/share/hadoop/common/hadoop-common-2.7.0.jar

**Comment by aseldawy** [comment]
You need to provide the type of shapes you're generating. You can use the following line for example:

$ bin/shadoop generate test mbr:0,0,1000000,1000000 shape:rect

I will modify the code to report a more meaningful error message.

**Comment by awhan-zot** [comment]
Apologies for that. Many thanks.
