### ISSUE TITLE
who can tell me spets to install the spatialhadoop on the hadoop?

### ISSUE THREAD

**Issue by GISerCAU** [aseldawy/spatialhadoop2#9]
Just like the title!

**Comment by CreativeCreamer** [comment]
1.              Download Spatial Hadoop tar file on existing Hadoop cluster machine
2.              Untar the downloaded SpatialHadoop bundle
3.              Copy SpatialHadoop/conf/* folder contents to $HADOOP_HOME/conf/ directory
4.              Copy SpatialHadoop/bin/* folder contents to $HADOOP_HOME/bin/ directory
5.              Copy SpatialHadoop/lib/* folder contents to $HADOOP_HOME/lib/ directory
6.              Copy spatialhadoop-x.x/spatialhadoop-main.jar file parallel to Hadoop lib folder, i.e., $HADOOP_HOME/* 

You can check the blog for more detail.. 
http://ingenioustext.blogspot.in/2015/03/start-with-spatialhadoop.html

**Comment by bigclove** [comment]
Thank you, C. C. i did this fellow the six steps; but have one error:
Error: Could not find or load main class edu.umn.cs.spatialHadoop.operations.Main

Are there any documents need me to configure?
Thanks!

**Comment by CreativeCreamer** [comment]
Have you tried running any command after configuring spatialHadoop ? If yes, then post the command as well.

**Comment by bigclove** [comment]
OK! JUST IT! thanks! 
guest@master:/usr/hadoop/bin$ /usr/hadoop/bin/shadoop
Error: Could not find or load main class edu.umn.cs.spatialHadoop.operations.Main

**Comment by CreativeCreamer** [comment]
Have you restarted the hadoop services after spatialhadoop configuration ?

**Comment by bigclove** [comment]
yes!  the hadoop version is 2.4.0. it is ok?

**Comment by CreativeCreamer** [comment]
I think it is not able to find the "spatialhadoop-main.jar" file in HADOOP_HOME directory parallel to $HADOOP_HOME/bin folder.
I have tried with Hadoop 2.2.0 and spatialhadoop-2.2 version, and above mentioned steps are working on that.

**Comment by bigclove** [comment]
can i give you an email about the details i did? thanks. post your email address!

**Comment by CreativeCreamer** [comment]
Post the steps here which you have tried.

**Comment by bigclove** [comment]
Step 1 
1、Download Spatial Hadoop tar file on existing Hadoop cluster machine
2、Untar the downloaded SpatialHadoop bundle
As the fig.1, left is the files of SpatialHadoop, right is the $HADOOP_HOME/*
 
![1](https://cloud.githubusercontent.com/assets/12046334/7265893/ec08cca0-e8d3-11e4-88cb-10e914141040.png)

Step 2 
1、Copy SpatialHadoop/conf/* folder contents to $HADOOP_HOME/conf/ directory
2、Copy SpatialHadoop/bin/* folder contents to $HADOOP_HOME/bin/ directory
3、Copy SpatialHadoop/lib/* folder contents to $HADOOP_HOME/lib/ directory
4、Copy spatialhadoop-x.x/spatialhadoop-main.jar file parallel to Hadoop lib folder, i.e., $HADOOP_HOME/*
 
![2](https://cloud.githubusercontent.com/assets/12046334/7265896/f302c696-e8d3-11e4-88c9-0901b59a31a2.png)

After finished：
/bin/shadoop                            /usr/hadoop/bin/
 
![3](https://cloud.githubusercontent.com/assets/12046334/7265899/fed1a726-e8d3-11e4-9edc-19b3189142d1.png)

/conf/spatial-site.xml                        /usr/hadoop/etc/hadoop/
 
![4](https://cloud.githubusercontent.com/assets/12046334/7265901/0bfde112-e8d4-11e4-9721-6e4997e0a43a.png)

**Comment by bigclove** [comment]
Next!
=====================================================
lib
![5](https://cloud.githubusercontent.com/assets/12046334/7265942/c60b8f28-e8d4-11e4-97da-aecd38058ed8.png)
Spatialhadoop-main.jar
![6](https://cloud.githubusercontent.com/assets/12046334/7265950/e190e220-e8d4-11e4-9416-13028b40f19b.png)
Then restart the hadoop!
![7](https://cloud.githubusercontent.com/assets/12046334/7265952/e8e123c8-e8d4-11e4-97b9-1a546c4c6049.png)
Then command
/usr/hadoop/bin/shadoop
![_en se pb1poinjhi_6yrc](https://cloud.githubusercontent.com/assets/12046334/7265956/f1cc0a48-e8d4-11e4-9a45-7e94b7330781.png)

**Comment by CreativeCreamer** [comment]
Check the entry for Main class in 'bin/shadoop' file
![a](https://cloud.githubusercontent.com/assets/9481639/7270846/b9c5ba5e-e8fc-11e4-811c-d9f533a02df1.jpg)

**Comment by bigclove** [comment]
now  it is not ok.


![image](https://cloud.githubusercontent.com/assets/12046334/7272554/4aef7954-e91e-11e4-8582-36ff6842400f.png)

![image](https://cloud.githubusercontent.com/assets/12046334/7272534/270b4c84-e91e-11e4-8bc6-8df538633a27.png)

**Comment by CreativeCreamer** [comment]
Not sure.. Why it is throwing exception for rangeQuery ? You can try running
"hadoop jar spatialhadoop-main.jar mbr" 
It should asks for "other parameters like inputfile".

**Comment by bigclove** [comment]
ok , i think i will try other version. thanks

**Comment by aseldawy** [comment]
It might be a little late but you need to get the right SpatialHadoop package based on your Hadoop version. For Hadoop 1.x, you need to download the file http://spatialhadoop.cs.umn.edu/downloads/spatialhadoop-2.3.tar.gz
For Hadoop 2.x (as in your case), you need to download an alternative version as the directory structure of Hadoop 2.x is different. Download the file
http://spatialhadoop.cs.umn.edu/downloads/spatialhadoop-2.3-2.tar.gz
You can also generate these files from the source code by running the ant task
ant package1
or
ant package2

Then, you need to extract the package (.tar.gz) file into your Hadoop home directory ($HADOOP_HOME). It will automatically place each file in the correct path. You can do this by running the following command
wget -qO- http://spatialhadoop.cs.umn.edu/downloads/spatialhadoop-2.3-2.tar.gz | tar --directory $HADOOP_HOME -xvz

Notice that you need to do this for EVERY machine in your cluster, not just the master node. After that, you need to restart the cluster to ensure that the new classes are loaded. You should be good to go from that point.

There are alternative techniques to install SpatialHadoop as you can find on the following page
http://spatialhadoop.cs.umn.edu/compile.html

Let me know if this resolves your problem.

**Comment by JeffersonEmanuel** [comment]
solução aseldawy!!  obrigado deu certo.

**Comment by kongshem** [comment]
@aseldawy You say that spatialhadoop-2.3.2 works with Hadoop 2.x, are you sure this covers Hadoop 2.6.0? Having the same issue as OP.

**Comment by aseldawy** [comment]
To run on Hadoop 2.x, you will have to compile it yourself from the source code. Please check the compilation guide at
https://github.com/aseldawy/spatialhadoop2/wiki/Compile-SpatialHadoop-from-source

**Comment by NishantBillava** [comment]
Hey,

I am not able to see the conf, lib folders when i untar the downloaded SpatialHadoop bundle.
Please guide me.

**Comment by fabianazioti** [comment]
`shadoop index test.rects sindex:grid test.grid shape:rect `

The following happens and does not generate the file:


INFO mapreduce.JobResourceUploader: Disabling Erasure Coding for path: /tmp/hadoop-yarn/staging/root/.staging/job_1543851353559_0004

INFO mapreduce.JobSubmitter: Cleaning up the staging area /tmp/hadoop-yarn/staging/root/.staging/job_1543851353559_0004

java.lang.NoSuchFieldError: LOG
at edu.umn.cs.spatialHadoop.mapred.SpatialInputFormat.listStatus(SpatialInputFormat.java:161)

at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:325)

at org.apache.hadoop.mapreduce.JobSubmitter.writeOldSplits(JobSubmitter.java:341)

at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:332)

at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:203)
.......
